appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: P0GBoCKNXKibeesas0Jk9ULorojIlzu0E6MeNVO9CgWQNN7SA1DrMOugiQ/7SvJ++VNQQFAqgpdoZMaurmnNaG0icgiMmUVxOZeidt46J4I8PrT7A2rs94WuR4o9CT6KOwIOUZ4qMCjg35CTP1T1v1kRAd4EoPX4OMF3tBphCOi6uogCyI8aO4VnUJYIixj6sDHSOwTohQWePOkvajhYjsflF5SbnV74jOp22dagnoQJxBwivdeY6thKeWPpMBfbuuaRT3a+UK8Zp1adYdIO107D3r45OdpTUP/xgwbfOv35zacKo/WEKUouZnVOo/GwDB0aME8uvxssRy3ogzfRHJj4TPuvhb6xEldxVCidHwaYSwCGAdBy0Am9AL1yvyMYZMQAiDciHp9pMMR7aLS4JlE15NIEbPRBU8LeT1Nl6oGoffZDZdyzAONk531PVdFGpkF1O24IfwsfU8034HolCYa/5eprvh4NG2s8uahp4J5mLnjhd+xANQnpBlk1HRQumngLVfPCBDTJHehX6/sIAZYoFHz0Uuj7eRs/q1wA5d8Bqtck+N0AYrpiDhkIFB9AR5/NkUq6l6OF/P0W83XiIVJlBOXtc1OQenYsYuqo+Hf7dKOz2Lok3fprlaAPZfHFZg4+aspdshKFrp5wBXOUb+SCkGNGNqpBdsLXk7cFzeg=}
provider:
  win: azure
bot:
  automerge: true
